### PR TITLE
fix(analytics toolbox): update pyproj and rasterio version

### PR DESCRIPTION
**Pull request by luipir**
Story details: https://app.shortcut.com/cartoteam/story/357569

### CODE REVIEW

**Comment by Jesus89** [comment]
If automatic & manual tests go well, we can merge

**Comment by luipir** [comment]
> If automatic & manual tests go well, we can merge

hmmmm... version is not available. The issue shuld depend on base image used. I there a reason to maintaain a older base image?

**Comment by luipir** [comment]
I would suspend this PR after more urgent PR about raster update.
I would update everythink to start with an well update version with higher version of all packages.
Any opinion @Jesus89 ?

**Comment by Jesus89** [comment]
Yes, let's close this for now, and we will update it for the new refactored version

**Pull request closed without merging**
